### ISSUE TITLE
Implement comprehensive security scanning with Dependabot, CodeQL, and Secret Scanning

### ISSUE THREAD

**Issue by pbonneville** [pbonneville/ai-common#11]
## Overview

This issue proposes implementing a comprehensive security scanning strategy for the ai-common repository using GitHub's native security features. This will help protect the codebase from vulnerabilities, security flaws, and accidental credential exposure.

## Why Security Scanning is Important

As this repository contains global configurations and utilities for AI-assisted development:
- **Dependency vulnerabilities** could compromise the entire development environment
- **Code vulnerabilities** in custom commands or utilities could create security risks
- **Exposed secrets** could lead to unauthorized access to services or APIs

### 1. GitHub Dependabot
**Purpose**: Automated dependency vulnerability scanning and updates

**What it does**:
- Monitors dependencies for known security vulnerabilities
- Automatically creates pull requests to update vulnerable dependencies
- Provides security advisories with detailed vulnerability information
- Supports multiple package ecosystems (npm, pip, bundler, etc.)

### 2. CodeQL Analysis
**Purpose**: Static Application Security Testing (SAST)

**What it does**:
- Analyzes code for security vulnerabilities and coding errors
- Detects issues like SQL injection, XSS, buffer overflows, and insecure data flow
- Provides detailed explanations and remediation guidance
- Runs automatically on pull requests and scheduled scans

### 3. Secret Scanning
**Purpose**: Prevent accidental credential commits

**What it does**:
- Scans commits for tokens, passwords, and API keys
- Blocks pushes containing detected secrets (when push protection is enabled)
- Alerts on historical secrets in the repository
- Partners with service providers to revoke exposed tokens automatically

### Step 1: Enable Dependabot
1. Navigate to Settings → Security & analysis
2. Enable "Dependabot alerts"
3. Enable "Dependabot security updates"
4. Create  for configuration:
   ```yaml
   version: 2
   updates:
     - package-ecosystem: "npm"
       directory: "/"
       schedule:
         interval: "weekly"
     - package-ecosystem: "pip"
       directory: "/"
       schedule:
         interval: "weekly"
   ```

### Step 2: Configure CodeQL Analysis
1. Enable CodeQL in Settings → Security & analysis
2. Create :
   ```yaml
   name: "CodeQL"
   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]
     schedule:
       - cron: '30 5 * * 1'
   
   jobs:
     analyze:
       name: Analyze
       runs-on: ubuntu-latest
       permissions:
         actions: read
         contents: read
         security-events: write
       
       steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       
       - name: Initialize CodeQL
         uses: github/codeql-action/init@v3
         with:
           languages: javascript, python
       
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3
   ```

### Step 3: Enable Secret Scanning
1. Navigate to Settings → Security & analysis
2. Enable "Secret scanning"
3. Enable "Push protection" to block commits with secrets
4. Configure custom patterns if needed for project-specific secrets

### Step 4: Security Policy
Create  to document:
- Security contact information
- Vulnerability reporting process
- Security update procedures
- Response timeline commitments

### Step 5: Branch Protection Rules
Update branch protection for :
- Require security checks to pass before merging
- Dismiss stale reviews when new commits are pushed
- Require review from CODEOWNERS for security-related files

## Benefits

1. **Proactive Security**: Catch vulnerabilities before they reach production
2. **Automated Updates**: Dependabot creates PRs for security patches
3. **Comprehensive Coverage**: Scan dependencies, code patterns, and secrets
4. **Developer Education**: Learn about security issues through detailed alerts
5. **Compliance**: Meet security requirements for enterprise environments

## Success Metrics

- Zero high/critical vulnerabilities in dependencies
- All security alerts addressed within 7 days
- No secrets committed to the repository
- Regular security scan completion (weekly/monthly)
- Documented security response procedures

## Additional Considerations

- Review and update  to exclude sensitive files
- Consider adding security-focused pre-commit hooks
- Document security best practices in contributing guidelines
- Regular security training for contributors

## Priority

**High** - Security should be implemented as soon as possible to protect the codebase and prevent potential vulnerabilities from being introduced.

## Labels

- enhancement
- security
- infrastructure
